package com.lunasdev.lunasdpi.vpn

class NativeBridgeConfig(
    @JvmField val mode: Int,
    @JvmField val tcpFragmentation: Boolean,
    @JvmField val fragmentSize: Int,
    @JvmField val httpHostCase: Boolean,
    @JvmField val httpSpacing: Boolean,
    @JvmField val httpMethodSpacing: Boolean,
    @JvmField val persistentFragment: Boolean,
    @JvmField val blockQuic: Boolean,
    @JvmField val dnsMode: Int,
    @JvmField val customDns: Array<String>,
    @JvmField val systemDns: Array<String>,
    @JvmField val ipv6Mode: Int,
    @JvmField val logLevel: Int,
    @JvmField val mtu: Int,
    @JvmField val tunDnsIpv4: String,
    @JvmField val ruleNames: Array<String>,
    @JvmField val ruleEnabled: BooleanArray,
    @JvmField val ruleStrategies: IntArray,
    @JvmField val ruleDomains: Array<String>,
    @JvmField val ruleFrag: BooleanArray,
    @JvmField val ruleFragSize: IntArray,
    @JvmField val ruleHostCase: BooleanArray,
    @JvmField val ruleSpacing: BooleanArray,
    @JvmField val ruleMethodSpacing: BooleanArray,
    @JvmField val hostNames: Array<String> = emptyArray(),
    @JvmField val hostIps: Array<String> = emptyArray(),
)
